theme: jekyll-theme-slate
title: Minh Long Vu
description: ##### Self-motivated and reliable while doing high-demanding works. Responsible and fast-learner individuals who willing to grow professionally. Patient and skillful to do precise work.
